server:
  port: 8080
  servlet:
    context-path: /bootcamp
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hrleosyodnubbh:88dd5283fbabb49ea2ffb2ac0345d80e69efb245616c47cf07973189e3b15236@ec2-184-73-198-174.compute-1.amazonaws.com:5432/d14so22ell4dcp
    username: hrleosyodnubbh
    password: 88dd5283fbabb49ea2ffb2ac0345d80e69efb245616c47cf07973189e3b15236
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander Dev Week